### ISSUE TITLE
`[[Mergers on x/x/xxxx, ]]`  is creating unwanted pages with namespaces

### ISSUE THREAD

**Issue by cannibalox** [hkgnp/logseq-mergepages-plugin#1]
upon merging pages, the resulting page has a page-ref  `[[Mergers on 1/4/2022, ]]` with the merged blocks underneath.
issues: 
* `[[Mergers on 1/4/2022, ]]` this date format is parsed as namespaces, creating unwanted pages [[mergers on 1]], [[4]], [[Mergers on 1/4/2022, ]]
*  there is an extra `,` at the end of the date
*  ideally the date should follow the date-formatter setting from config.edn

**Comment by benjypng** [comment]
Thanks @cannibalox. I am not able to re-produce this. 

![Screenshot 2022-01-05 at 3 18 31 AM](https://user-images.githubusercontent.com/47936793/148112087-89059ee1-134a-447f-9c5e-c5ffdc6b2ff9.png)

Do you mind sharing a screenshot of your issue, please? As well as any information about how your page is setup so that I can try to reproduce it.

Thanks!

**Comment by cannibalox** [comment]
weird, did you disable namespaces ? the slash is the delimiter for namespaces in logseq, by default [[mergers on 05/01/2022]] is parsed as a namespaced link, like [[movie/star wars]].
 will send a screenshot later on, not in front of a computer atm.

**Comment by benjypng** [comment]
Oh! How do you disable name spacing? I have no idea it can be done!
I currently use name spacing for my other pages and it works fine though.

But good suggestion to have it follow the dating format set by the user. Will add that in when I’ve some free time.

**Comment by cannibalox** [comment]
hmm, if you go to page [[Mergers on 05/01/2022]], don't you see the section with the namespace hierarchy ?
it should show that unwanted (?) extra pages [[Mergers on 05]] , [[01]] and [[2022]] were created 
![image](https://user-images.githubusercontent.com/4605693/148317970-df8e8281-205e-4ff7-a882-13a54c986877.png)

imo the simplest workaround would be to use `-` delimiter instead of `/` for the date

**Comment by benjypng** [comment]
I've added in support for user preferred date format in the latest version in the marketplace (v1.4). Do update and see if it solves your problem for new merges.

Will close this issue for now, but please re-open if need be.

Thanks!
