### ISSUE TITLE
Can't merge children blocks when merging linked references

### ISSUE THREAD

**Issue by byheaven** [hkgnp/logseq-mergepages-plugin#3]
The children blocks can't be included with Logseq 0.8.16 (maybe from earlier versions) .

https://user-images.githubusercontent.com/30173023/212271412-96946435-0b17-4c62-9d26-868b1115ea89.mov

**Comment by benjypng** [comment]
Pls try v1.6.3.

**Comment by byheaven** [comment]
<img width="425" alt="image" src="https://user-images.githubusercontent.com/30173023/212297063-c91202a5-eafa-42ba-aa75-6f6d5c4219bf.png">
The children blocks can be included now, however there is a * before each block...
Another problem is that if the page has referenced itself, the contents are also merged again.

**Comment by benjypng** [comment]
> <img alt="image" width="425" src="https://user-images.githubusercontent.com/30173023/212297063-c91202a5-eafa-42ba-aa75-6f6d5c4219bf.png">
> 
> The children blocks can be included now, however there is a * before each block... Another problem is that if the page has referenced itself, the contents are also merged again.

(1) I am not able to reproduce the * issue though. I don't get a * when I merge.
(2) Sorry I am not sure what you mean by that. Do you have a screenshot? If it appears in the Linked References, it should be merged.

**Comment by byheaven** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/30173023/212520133-1149a1df-db92-4676-84a9-b28d7910056c.png">
<img width="938" alt="image" src="https://user-images.githubusercontent.com/30173023/212520148-ff12a52e-aec8-49b5-8157-aeecc6d29046.png">
Sure, as shown in the first screenshot, the page [[test]] is referenced by itself. Then I trigger the merge. Now it comes with two duplicated lines which means the content already in the pages is also merged.

P.S. The problem of the strange * is gone after I reinstall the plugin and restart logseq.

**Comment by benjypng** [comment]
Please try v1.6.4.

**Comment by byheaven** [comment]
Works like a charm! Thank you!
